name: Metrics embed

on:
  schedule:
    - cron: '0 0 1 * *' # Run once a month

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Metrics
      uses: lowlighter/metrics@v3.34
      with:
        filename: metrics.plugin.screenshot.svg
        token: NOT_NEEDED
        base: ''
        plugin_screenshot: 'yes'
        plugin_screenshot_title: ''
        plugin_screenshot_url: 'https://riannegreiros.dev'
